server:
  port: 8082

spring:
  webflux:
    base-path: /auth-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: postgres
  jpa:
    show-sql: true

  flyway:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    user: postgres
    password: postgres
    enabled: true

springbootwebfluxjjwt:
  jjwt:
    secret: h4f8093h4f983yhrt9834hr0934hf0hf493g493gf438rh438th34g34g
    expiration: 36000000
  password:
    encoder:
      secret: mysecret
      iteration: 33
      keylength: 256


