server:
  port: 8081
spring:
  webflux:
    base-path: /moderate-service
integrations:
  core-service:
    url: http://localhost:8080/core-service
    connect-timeout: 500
    read-timeout: 10000
    write-timeout: 5000

