server:
  port: 8080
  servlet:
    context-path: /core-service

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/postgres?currentSchema=public
    username: postgres
    password: postgres

  jpa:
    show-sql: true
  webflux:
    base-path: /core-service

upload:
  path: /dem