spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/postgres?currentSchema=public
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  webflux:
    base-path: /core-service
  flyway:
    url: jdbc:postgresql://localhost:5433/postgres?currentSchema=public
    user: postgres
    password: postgres
    enabled: true
upload:
  path: /dem
server:
  port: 8080