version: '3.1'

services:
  db:
    image: mysql:5.7
    domainname: mysql
    ports:
      - "5433:3306"
    environment:
      MYSQL_DATABASE: 'diplom'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USERNAME: 'sa'
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "postgres"]
      interval: 5s
      timeout: 1s
      retries: 2